apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"mark-potter-dev"}}
  creationTimestamp: "2026-02-03T22:31:09Z"
  labels:
    kubernetes.io/metadata.name: mark-potter-dev
  name: mark-potter-dev
  resourceVersion: "9151169"
  uid: 8c49b09c-21cd-4a5e-a822-decb6703877c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"mark-potter-dev"}}
  creationTimestamp: "2026-02-03T22:31:09Z"
  labels:
    kubernetes.io/metadata.name: mark-potter-dev
  name: mark-potter-dev
  resourceVersion: "9151169"
  uid: 8c49b09c-21cd-4a5e-a822-decb6703877c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"mark-potter-dev"}}
  creationTimestamp: "2026-02-03T22:31:09Z"
  labels:
    kubernetes.io/metadata.name: mark-potter-dev
  name: mark-potter-dev
  resourceVersion: "9151169"
  uid: 8c49b09c-21cd-4a5e-a822-decb6703877c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"mark-potter-dev"}}
  creationTimestamp: "2026-02-03T22:31:09Z"
  labels:
    kubernetes.io/metadata.name: mark-potter-dev
  name: mark-potter-dev
  resourceVersion: "9151169"
  uid: 8c49b09c-21cd-4a5e-a822-decb6703877c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
